extends:
  - airbnb-base
  - plugin:prettier/recommended
  - plugin:jest/recommended
plugins:
  - import
  - jest
rules:
  import/no-unresolved: 'error'
  import/prefer-default-export: 'off'
  no-use-before-define: 'off'
  no-underscore-dangle: 'off'
  no-console: 'error'
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
  class-methods-use-this: 'off'
env:
  jest/globals: true
  node: true
  es6: true
  jest: true
