name: application
on: [push]

jobs:
  build-release:
    name: Build and Release
    runs-on: ubuntu-latest
    if: ${{ github.event.pusher.name != '@lerna-bot' }}
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm ci
          npm run bootstrap:ci
          npm run lint:ci
          npm run test:ci
        env:
          CI: true
      - name: Deploy
        run: npm run deploy:ci
      - name: Release
        run: |
          git config user.name "@lerna-bot"
          git config user.email "lerna-bot@github.com"
          npm run version:ci
